/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.toursandtravels.api.controller;

import com.toursandtravels.api.model.BookTravelFormRequest;
import com.toursandtravels.api.model.BookTravelFormWithCarModelRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-08-29T14:44:32.943+05:30[Asia/Calcutta]")
@Validated
public interface BookTravelNowApi {

    @Operation(summary = "Submit a travel booking request", description = "", tags={ "Travel Booking" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Travel request submitted successfully"),
        
        @ApiResponse(responseCode = "400", description = "Invalid input") })
    @RequestMapping(value = "/bookTravelNow",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> bookTravelJourny(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema())  @RequestBody BookTravelFormWithCarModelRequest body);

}

